// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/sms/sms.proto

package go_micro_srv_sms

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListRequest struct {
	Page                 int64    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab867e236c3ccf27, []int{0}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

func (m *ListRequest) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

type ListResponse struct {
	Page                 int64    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab867e236c3ccf27, []int{1}
}

func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

type TemplateRequest struct {
	Page                 int64    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TemplateRequest) Reset()         { *m = TemplateRequest{} }
func (m *TemplateRequest) String() string { return proto.CompactTextString(m) }
func (*TemplateRequest) ProtoMessage()    {}
func (*TemplateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab867e236c3ccf27, []int{2}
}

func (m *TemplateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TemplateRequest.Unmarshal(m, b)
}
func (m *TemplateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TemplateRequest.Marshal(b, m, deterministic)
}
func (m *TemplateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TemplateRequest.Merge(m, src)
}
func (m *TemplateRequest) XXX_Size() int {
	return xxx_messageInfo_TemplateRequest.Size(m)
}
func (m *TemplateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TemplateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TemplateRequest proto.InternalMessageInfo

func (m *TemplateRequest) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

type TemplateResponse struct {
	Page                 int64    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TemplateResponse) Reset()         { *m = TemplateResponse{} }
func (m *TemplateResponse) String() string { return proto.CompactTextString(m) }
func (*TemplateResponse) ProtoMessage()    {}
func (*TemplateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab867e236c3ccf27, []int{3}
}

func (m *TemplateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TemplateResponse.Unmarshal(m, b)
}
func (m *TemplateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TemplateResponse.Marshal(b, m, deterministic)
}
func (m *TemplateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TemplateResponse.Merge(m, src)
}
func (m *TemplateResponse) XXX_Size() int {
	return xxx_messageInfo_TemplateResponse.Size(m)
}
func (m *TemplateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TemplateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TemplateResponse proto.InternalMessageInfo

func (m *TemplateResponse) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

type PoviderRequest struct {
	Page                 int64    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PoviderRequest) Reset()         { *m = PoviderRequest{} }
func (m *PoviderRequest) String() string { return proto.CompactTextString(m) }
func (*PoviderRequest) ProtoMessage()    {}
func (*PoviderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab867e236c3ccf27, []int{4}
}

func (m *PoviderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PoviderRequest.Unmarshal(m, b)
}
func (m *PoviderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PoviderRequest.Marshal(b, m, deterministic)
}
func (m *PoviderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PoviderRequest.Merge(m, src)
}
func (m *PoviderRequest) XXX_Size() int {
	return xxx_messageInfo_PoviderRequest.Size(m)
}
func (m *PoviderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PoviderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PoviderRequest proto.InternalMessageInfo

func (m *PoviderRequest) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

type PoviderResponse struct {
	Page                 int64    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PoviderResponse) Reset()         { *m = PoviderResponse{} }
func (m *PoviderResponse) String() string { return proto.CompactTextString(m) }
func (*PoviderResponse) ProtoMessage()    {}
func (*PoviderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab867e236c3ccf27, []int{5}
}

func (m *PoviderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PoviderResponse.Unmarshal(m, b)
}
func (m *PoviderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PoviderResponse.Marshal(b, m, deterministic)
}
func (m *PoviderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PoviderResponse.Merge(m, src)
}
func (m *PoviderResponse) XXX_Size() int {
	return xxx_messageInfo_PoviderResponse.Size(m)
}
func (m *PoviderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PoviderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PoviderResponse proto.InternalMessageInfo

func (m *PoviderResponse) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func init() {
	proto.RegisterType((*ListRequest)(nil), "go.micro.srv.sms.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "go.micro.srv.sms.ListResponse")
	proto.RegisterType((*TemplateRequest)(nil), "go.micro.srv.sms.TemplateRequest")
	proto.RegisterType((*TemplateResponse)(nil), "go.micro.srv.sms.TemplateResponse")
	proto.RegisterType((*PoviderRequest)(nil), "go.micro.srv.sms.PoviderRequest")
	proto.RegisterType((*PoviderResponse)(nil), "go.micro.srv.sms.PoviderResponse")
}

func init() { proto.RegisterFile("proto/sms/sms.proto", fileDescriptor_ab867e236c3ccf27) }

var fileDescriptor_ab867e236c3ccf27 = []byte{
	// 218 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0xce, 0x2d, 0x06, 0x61, 0x3d, 0x30, 0x4f, 0x48, 0x20, 0x3d, 0x5f, 0x2f, 0x37,
	0x33, 0xb9, 0x28, 0x5f, 0xaf, 0xb8, 0xa8, 0x4c, 0xaf, 0x38, 0xb7, 0x58, 0x49, 0x91, 0x8b, 0xdb,
	0x27, 0xb3, 0xb8, 0x24, 0x28, 0xb5, 0xb0, 0x34, 0xb5, 0xb8, 0x44, 0x48, 0x88, 0x8b, 0xa5, 0x20,
	0x31, 0x3d, 0x55, 0x82, 0x51, 0x81, 0x51, 0x83, 0x39, 0x08, 0xcc, 0x56, 0x52, 0xe2, 0xe2, 0x81,
	0x28, 0x29, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0xc5, 0xaa, 0x46, 0x95, 0x8b, 0x3f, 0x24, 0x35, 0xb7,
	0x20, 0x27, 0xb1, 0x24, 0x15, 0x9f, 0x51, 0x6a, 0x5c, 0x02, 0x08, 0x65, 0x78, 0x8c, 0x53, 0xe1,
	0xe2, 0x0b, 0xc8, 0x2f, 0xcb, 0x4c, 0x49, 0x2d, 0xc2, 0x67, 0x9a, 0x2a, 0x17, 0x3f, 0x5c, 0x15,
	0x6e, 0xc3, 0x8c, 0xbe, 0x32, 0x72, 0x31, 0x07, 0xe7, 0x16, 0x0b, 0xb9, 0x73, 0xb1, 0x80, 0xfc,
	0x21, 0x24, 0xab, 0x87, 0x1e, 0x0a, 0x7a, 0x48, 0x41, 0x20, 0x25, 0x87, 0x4b, 0x1a, 0x62, 0x85,
	0x12, 0x83, 0x50, 0x30, 0x17, 0x07, 0xcc, 0x17, 0x42, 0x8a, 0x98, 0xaa, 0xd1, 0x02, 0x42, 0x4a,
	0x09, 0x9f, 0x12, 0xb8, 0xa1, 0x01, 0x5c, 0xec, 0x50, 0xcf, 0x08, 0x29, 0x60, 0x6a, 0x40, 0x0d,
	0x0d, 0x29, 0x45, 0x3c, 0x2a, 0x60, 0x26, 0x26, 0xb1, 0x81, 0xe3, 0xdc, 0x18, 0x10, 0x00, 0x00,
	0xff, 0xff, 0x6e, 0x50, 0x4a, 0x48, 0x0a, 0x02, 0x00, 0x00,
}
