// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/auth/auth.proto

package go_micro_srv_user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NameRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NameRequest) Reset()         { *m = NameRequest{} }
func (m *NameRequest) String() string { return proto.CompactTextString(m) }
func (*NameRequest) ProtoMessage()    {}
func (*NameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{0}
}

func (m *NameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NameRequest.Unmarshal(m, b)
}
func (m *NameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NameRequest.Marshal(b, m, deterministic)
}
func (m *NameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NameRequest.Merge(m, src)
}
func (m *NameRequest) XXX_Size() int {
	return xxx_messageInfo_NameRequest.Size(m)
}
func (m *NameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NameRequest proto.InternalMessageInfo

func (m *NameRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NameRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type MobileRequest struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MobileRequest) Reset()         { *m = MobileRequest{} }
func (m *MobileRequest) String() string { return proto.CompactTextString(m) }
func (*MobileRequest) ProtoMessage()    {}
func (*MobileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{1}
}

func (m *MobileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MobileRequest.Unmarshal(m, b)
}
func (m *MobileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MobileRequest.Marshal(b, m, deterministic)
}
func (m *MobileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MobileRequest.Merge(m, src)
}
func (m *MobileRequest) XXX_Size() int {
	return xxx_messageInfo_MobileRequest.Size(m)
}
func (m *MobileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MobileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MobileRequest proto.InternalMessageInfo

func (m *MobileRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *MobileRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type AuthResponse struct {
	Header               string   `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	ExpiresAt            string   `protobuf:"bytes,3,opt,name=expiresAt,proto3" json:"expiresAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthResponse) Reset()         { *m = AuthResponse{} }
func (m *AuthResponse) String() string { return proto.CompactTextString(m) }
func (*AuthResponse) ProtoMessage()    {}
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{2}
}

func (m *AuthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthResponse.Unmarshal(m, b)
}
func (m *AuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthResponse.Marshal(b, m, deterministic)
}
func (m *AuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthResponse.Merge(m, src)
}
func (m *AuthResponse) XXX_Size() int {
	return xxx_messageInfo_AuthResponse.Size(m)
}
func (m *AuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthResponse proto.InternalMessageInfo

func (m *AuthResponse) GetHeader() string {
	if m != nil {
		return m.Header
	}
	return ""
}

func (m *AuthResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *AuthResponse) GetExpiresAt() string {
	if m != nil {
		return m.ExpiresAt
	}
	return ""
}

func init() {
	proto.RegisterType((*NameRequest)(nil), "go.micro.srv.user.NameRequest")
	proto.RegisterType((*MobileRequest)(nil), "go.micro.srv.user.MobileRequest")
	proto.RegisterType((*AuthResponse)(nil), "go.micro.srv.user.AuthResponse")
}

func init() { proto.RegisterFile("proto/auth/auth.proto", fileDescriptor_82b5829f48cfb8e5) }

var fileDescriptor_82b5829f48cfb8e5 = []byte{
	// 248 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0x31, 0x4f, 0x84, 0x40,
	0x10, 0x85, 0x45, 0x91, 0x78, 0xa3, 0x16, 0x4e, 0xd4, 0x90, 0x8b, 0xd1, 0x0b, 0x95, 0xd5, 0x9a,
	0x68, 0x69, 0x2c, 0xae, 0xb4, 0x38, 0x0b, 0x4a, 0xbb, 0xbd, 0x63, 0x22, 0x44, 0x61, 0x70, 0x67,
	0x51, 0x7f, 0x8e, 0x3f, 0xd5, 0x30, 0xac, 0xe7, 0x19, 0x29, 0x6c, 0xc8, 0xbc, 0x37, 0xbc, 0x2f,
	0xfb, 0x76, 0xe1, 0xa4, 0x75, 0xec, 0xf9, 0xca, 0x76, 0xbe, 0xd4, 0x8f, 0x51, 0x8d, 0x47, 0x4f,
	0x6c, 0xea, 0x6a, 0xe5, 0xd8, 0x88, 0x7b, 0x33, 0x9d, 0x90, 0xcb, 0xee, 0x60, 0xff, 0xc1, 0xd6,
	0x94, 0xd3, 0x6b, 0x47, 0xe2, 0x11, 0x21, 0x6e, 0x6c, 0x4d, 0x69, 0x34, 0x8b, 0x2e, 0x27, 0xb9,
	0xce, 0x38, 0x85, 0xbd, 0xd6, 0x8a, 0xbc, 0xb3, 0x2b, 0xd2, 0x6d, 0xf5, 0xd7, 0x3a, 0xbb, 0x85,
	0xc3, 0x05, 0x2f, 0xab, 0x97, 0x35, 0xe0, 0x14, 0x92, 0x5a, 0x8d, 0x80, 0x08, 0xaa, 0x07, 0xaf,
	0xb8, 0xa0, 0x00, 0xd0, 0x39, 0x7b, 0x84, 0x83, 0x79, 0xe7, 0xcb, 0x9c, 0xa4, 0xe5, 0x46, 0xa8,
	0xcf, 0x96, 0x64, 0x0b, 0x72, 0xdf, 0xd9, 0x41, 0xe1, 0x31, 0xec, 0x7a, 0x7e, 0xa6, 0x26, 0x84,
	0x07, 0x81, 0x67, 0x30, 0xa1, 0x8f, 0xb6, 0x72, 0x24, 0x73, 0x9f, 0xee, 0xe8, 0xe6, 0xc7, 0xb8,
	0xfe, 0x8c, 0x20, 0xee, 0xe1, 0x78, 0x0f, 0x71, 0x5f, 0x10, 0xcf, 0xcd, 0x9f, 0xf2, 0x66, 0xa3,
	0xf9, 0xf4, 0x62, 0x64, 0xbf, 0x79, 0xba, 0x6c, 0x0b, 0x17, 0x90, 0x0c, 0x65, 0x71, 0x36, 0xf2,
	0xf3, 0xaf, 0x7b, 0xf8, 0x07, 0x6e, 0x99, 0xe8, 0xa3, 0xdc, 0x7c, 0x05, 0x00, 0x00, 0xff, 0xff,
	0x7e, 0x01, 0x36, 0xd7, 0xad, 0x01, 0x00, 0x00,
}
