// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user/user.proto

package go_micro_srv_user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Mobile               string   `protobuf:"bytes,3,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{0}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CreateRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *CreateRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type CreateResponse struct {
	Id                   int64          `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreateRequest        *CreateRequest `protobuf:"bytes,2,opt,name=CreateRequest,proto3" json:"CreateRequest,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{1}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CreateResponse) GetCreateRequest() *CreateRequest {
	if m != nil {
		return m.CreateRequest
	}
	return nil
}

type EditRequest struct {
	Id                   int64          `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreateRequest        *CreateRequest `protobuf:"bytes,2,opt,name=CreateRequest,proto3" json:"CreateRequest,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *EditRequest) Reset()         { *m = EditRequest{} }
func (m *EditRequest) String() string { return proto.CompactTextString(m) }
func (*EditRequest) ProtoMessage()    {}
func (*EditRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{2}
}

func (m *EditRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditRequest.Unmarshal(m, b)
}
func (m *EditRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditRequest.Marshal(b, m, deterministic)
}
func (m *EditRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditRequest.Merge(m, src)
}
func (m *EditRequest) XXX_Size() int {
	return xxx_messageInfo_EditRequest.Size(m)
}
func (m *EditRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EditRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EditRequest proto.InternalMessageInfo

func (m *EditRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *EditRequest) GetCreateRequest() *CreateRequest {
	if m != nil {
		return m.CreateRequest
	}
	return nil
}

type EditResponse struct {
	Id                   int64          `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreateRequest        *CreateRequest `protobuf:"bytes,2,opt,name=CreateRequest,proto3" json:"CreateRequest,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *EditResponse) Reset()         { *m = EditResponse{} }
func (m *EditResponse) String() string { return proto.CompactTextString(m) }
func (*EditResponse) ProtoMessage()    {}
func (*EditResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{3}
}

func (m *EditResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditResponse.Unmarshal(m, b)
}
func (m *EditResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditResponse.Marshal(b, m, deterministic)
}
func (m *EditResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditResponse.Merge(m, src)
}
func (m *EditResponse) XXX_Size() int {
	return xxx_messageInfo_EditResponse.Size(m)
}
func (m *EditResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EditResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EditResponse proto.InternalMessageInfo

func (m *EditResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *EditResponse) GetCreateRequest() *CreateRequest {
	if m != nil {
		return m.CreateRequest
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateRequest)(nil), "go.micro.srv.user.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "go.micro.srv.user.CreateResponse")
	proto.RegisterType((*EditRequest)(nil), "go.micro.srv.user.EditRequest")
	proto.RegisterType((*EditResponse)(nil), "go.micro.srv.user.EditResponse")
}

func init() { proto.RegisterFile("proto/user/user.proto", fileDescriptor_9b283a848145d6b7) }

var fileDescriptor_9b283a848145d6b7 = []byte{
	// 254 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x52, 0xcb, 0x4e, 0xc3, 0x30,
	0x10, 0x24, 0x69, 0x88, 0x60, 0x0b, 0x95, 0x58, 0x01, 0x8a, 0x72, 0x80, 0x92, 0x13, 0x27, 0x23,
	0x95, 0x4f, 0x40, 0x20, 0x71, 0x42, 0x8a, 0xc4, 0x07, 0xb8, 0x78, 0x01, 0x4b, 0x75, 0x1d, 0xbc,
	0x2e, 0xfc, 0x0f, 0x5f, 0x8a, 0xba, 0x26, 0x88, 0xf2, 0x3c, 0xf5, 0x12, 0x65, 0x76, 0xc6, 0x3b,
	0x33, 0x96, 0xe1, 0xa0, 0x0b, 0x3e, 0xfa, 0xb3, 0x05, 0x53, 0x90, 0x8f, 0x12, 0x8c, 0x7b, 0x0f,
	0x5e, 0x39, 0x7b, 0x17, 0xbc, 0xe2, 0xf0, 0xac, 0x96, 0x44, 0xe3, 0x60, 0xf7, 0x22, 0x90, 0x8e,
	0xd4, 0xd2, 0xd3, 0x82, 0x38, 0x22, 0x42, 0x31, 0xd7, 0x8e, 0xaa, 0x6c, 0x9c, 0x9d, 0x6e, 0xb7,
	0xf2, 0x8f, 0x35, 0x6c, 0x75, 0x9a, 0xf9, 0xc5, 0x07, 0x53, 0xe5, 0x32, 0xff, 0xc0, 0x78, 0x08,
	0xa5, 0xf3, 0x53, 0x3b, 0xa3, 0x6a, 0x20, 0xcc, 0x3b, 0xc2, 0x7d, 0xd8, 0x24, 0xa7, 0xed, 0xac,
	0x2a, 0x64, 0x9c, 0x40, 0xf3, 0x08, 0xa3, 0xde, 0x8e, 0x3b, 0x3f, 0x67, 0xc2, 0x11, 0xe4, 0xd6,
	0x88, 0xdb, 0xa0, 0xcd, 0xad, 0xc1, 0xab, 0x2f, 0x81, 0xc4, 0x70, 0x38, 0x19, 0xab, 0x6f, 0xd9,
	0xd5, 0x8a, 0xae, 0x5d, 0x3d, 0xd6, 0x10, 0x0c, 0x2f, 0x8d, 0x8d, 0x7d, 0xad, 0x75, 0xd9, 0xdc,
	0xc3, 0x4e, 0xb2, 0x59, 0x6f, 0x9d, 0xc9, 0x6b, 0x06, 0xc5, 0x2d, 0x53, 0xc0, 0x1b, 0x28, 0x13,
	0x83, 0xff, 0xee, 0xa8, 0x4f, 0xfe, 0x50, 0xa4, 0xbc, 0xcd, 0x06, 0x5e, 0x43, 0xb1, 0x6c, 0x80,
	0x47, 0x3f, 0x88, 0x3f, 0xdd, 0x60, 0x7d, 0xfc, 0x2b, 0xdf, 0xaf, 0x9a, 0x96, 0xf2, 0xcc, 0xce,
	0xdf, 0x02, 0x00, 0x00, 0xff, 0xff, 0x52, 0xdc, 0xf1, 0xde, 0x7f, 0x02, 0x00, 0x00,
}
