// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/send/send.proto

package go_micro_srv_sms

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BizType int32

const (
	BizType_login              BizType = 0
	BizType_register           BizType = 1
	BizType_Edit_Password      BizType = 2
	BizType_Tempreset_Password BizType = 3
)

var BizType_name = map[int32]string{
	0: "login",
	1: "register",
	2: "Edit_Password",
	3: "Tempreset_Password",
}

var BizType_value = map[string]int32{
	"login":              0,
	"register":           1,
	"Edit_Password":      2,
	"Tempreset_Password": 3,
}

func (x BizType) String() string {
	return proto.EnumName(BizType_name, int32(x))
}

func (BizType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_535ada0d8e4e45b5, []int{0}
}

type Mode int32

const (
	Mode_Code   Mode = 0
	Mode_Notice Mode = 1
)

var Mode_name = map[int32]string{
	0: "Code",
	1: "Notice",
}

var Mode_value = map[string]int32{
	"Code":   0,
	"Notice": 1,
}

func (x Mode) String() string {
	return proto.EnumName(Mode_name, int32(x))
}

func (Mode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_535ada0d8e4e45b5, []int{1}
}

type Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_535ada0d8e4e45b5, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

type MapType struct {
	Key                  int32    `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MapType) Reset()         { *m = MapType{} }
func (m *MapType) String() string { return proto.CompactTextString(m) }
func (*MapType) ProtoMessage()    {}
func (*MapType) Descriptor() ([]byte, []int) {
	return fileDescriptor_535ada0d8e4e45b5, []int{1}
}

func (m *MapType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MapType.Unmarshal(m, b)
}
func (m *MapType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MapType.Marshal(b, m, deterministic)
}
func (m *MapType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MapType.Merge(m, src)
}
func (m *MapType) XXX_Size() int {
	return xxx_messageInfo_MapType.Size(m)
}
func (m *MapType) XXX_DiscardUnknown() {
	xxx_messageInfo_MapType.DiscardUnknown(m)
}

var xxx_messageInfo_MapType proto.InternalMessageInfo

func (m *MapType) GetKey() int32 {
	if m != nil {
		return m.Key
	}
	return 0
}

func (m *MapType) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type BizTypeResponse struct {
	List                 []*MapType `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *BizTypeResponse) Reset()         { *m = BizTypeResponse{} }
func (m *BizTypeResponse) String() string { return proto.CompactTextString(m) }
func (*BizTypeResponse) ProtoMessage()    {}
func (*BizTypeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_535ada0d8e4e45b5, []int{2}
}

func (m *BizTypeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BizTypeResponse.Unmarshal(m, b)
}
func (m *BizTypeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BizTypeResponse.Marshal(b, m, deterministic)
}
func (m *BizTypeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BizTypeResponse.Merge(m, src)
}
func (m *BizTypeResponse) XXX_Size() int {
	return xxx_messageInfo_BizTypeResponse.Size(m)
}
func (m *BizTypeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BizTypeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BizTypeResponse proto.InternalMessageInfo

func (m *BizTypeResponse) GetList() []*MapType {
	if m != nil {
		return m.List
	}
	return nil
}

type CodeRequest struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	BizType              BizType  `protobuf:"varint,2,opt,name=bizType,proto3,enum=go.micro.srv.sms.BizType" json:"bizType,omitempty"`
	Expires              int64    `protobuf:"varint,3,opt,name=expires,proto3" json:"expires,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CodeRequest) Reset()         { *m = CodeRequest{} }
func (m *CodeRequest) String() string { return proto.CompactTextString(m) }
func (*CodeRequest) ProtoMessage()    {}
func (*CodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_535ada0d8e4e45b5, []int{3}
}

func (m *CodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CodeRequest.Unmarshal(m, b)
}
func (m *CodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CodeRequest.Marshal(b, m, deterministic)
}
func (m *CodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CodeRequest.Merge(m, src)
}
func (m *CodeRequest) XXX_Size() int {
	return xxx_messageInfo_CodeRequest.Size(m)
}
func (m *CodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CodeRequest proto.InternalMessageInfo

func (m *CodeRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *CodeRequest) GetBizType() BizType {
	if m != nil {
		return m.BizType
	}
	return BizType_login
}

func (m *CodeRequest) GetExpires() int64 {
	if m != nil {
		return m.Expires
	}
	return 0
}

type CodeResponse struct {
	Success              bool                 `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ExpiresAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=expiresAt,proto3" json:"expiresAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CodeResponse) Reset()         { *m = CodeResponse{} }
func (m *CodeResponse) String() string { return proto.CompactTextString(m) }
func (*CodeResponse) ProtoMessage()    {}
func (*CodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_535ada0d8e4e45b5, []int{4}
}

func (m *CodeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CodeResponse.Unmarshal(m, b)
}
func (m *CodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CodeResponse.Marshal(b, m, deterministic)
}
func (m *CodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CodeResponse.Merge(m, src)
}
func (m *CodeResponse) XXX_Size() int {
	return xxx_messageInfo_CodeResponse.Size(m)
}
func (m *CodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CodeResponse proto.InternalMessageInfo

func (m *CodeResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *CodeResponse) GetExpiresAt() *timestamp.Timestamp {
	if m != nil {
		return m.ExpiresAt
	}
	return nil
}

type ValidateRequest struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	BizType              BizType  `protobuf:"varint,2,opt,name=bizType,proto3,enum=go.micro.srv.sms.BizType" json:"bizType,omitempty"`
	Code                 string   `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateRequest) Reset()         { *m = ValidateRequest{} }
func (m *ValidateRequest) String() string { return proto.CompactTextString(m) }
func (*ValidateRequest) ProtoMessage()    {}
func (*ValidateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_535ada0d8e4e45b5, []int{5}
}

func (m *ValidateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateRequest.Unmarshal(m, b)
}
func (m *ValidateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateRequest.Marshal(b, m, deterministic)
}
func (m *ValidateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateRequest.Merge(m, src)
}
func (m *ValidateRequest) XXX_Size() int {
	return xxx_messageInfo_ValidateRequest.Size(m)
}
func (m *ValidateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateRequest proto.InternalMessageInfo

func (m *ValidateRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *ValidateRequest) GetBizType() BizType {
	if m != nil {
		return m.BizType
	}
	return BizType_login
}

func (m *ValidateRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type ValidateResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateResponse) Reset()         { *m = ValidateResponse{} }
func (m *ValidateResponse) String() string { return proto.CompactTextString(m) }
func (*ValidateResponse) ProtoMessage()    {}
func (*ValidateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_535ada0d8e4e45b5, []int{6}
}

func (m *ValidateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateResponse.Unmarshal(m, b)
}
func (m *ValidateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateResponse.Marshal(b, m, deterministic)
}
func (m *ValidateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateResponse.Merge(m, src)
}
func (m *ValidateResponse) XXX_Size() int {
	return xxx_messageInfo_ValidateResponse.Size(m)
}
func (m *ValidateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateResponse proto.InternalMessageInfo

func (m *ValidateResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterEnum("go.micro.srv.sms.BizType", BizType_name, BizType_value)
	proto.RegisterEnum("go.micro.srv.sms.Mode", Mode_name, Mode_value)
	proto.RegisterType((*Request)(nil), "go.micro.srv.sms.Request")
	proto.RegisterType((*MapType)(nil), "go.micro.srv.sms.MapType")
	proto.RegisterType((*BizTypeResponse)(nil), "go.micro.srv.sms.BizTypeResponse")
	proto.RegisterType((*CodeRequest)(nil), "go.micro.srv.sms.CodeRequest")
	proto.RegisterType((*CodeResponse)(nil), "go.micro.srv.sms.CodeResponse")
	proto.RegisterType((*ValidateRequest)(nil), "go.micro.srv.sms.ValidateRequest")
	proto.RegisterType((*ValidateResponse)(nil), "go.micro.srv.sms.ValidateResponse")
}

func init() { proto.RegisterFile("proto/send/send.proto", fileDescriptor_535ada0d8e4e45b5) }

var fileDescriptor_535ada0d8e4e45b5 = []byte{
	// 451 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x92, 0xcb, 0x6f, 0xd3, 0x40,
	0x10, 0xc6, 0xe3, 0xda, 0x89, 0xe3, 0x49, 0xa1, 0x66, 0x04, 0x95, 0xb1, 0x78, 0x04, 0x9f, 0xa2,
	0x0a, 0x36, 0x22, 0xbd, 0x70, 0xe4, 0x21, 0x84, 0x38, 0x04, 0xa1, 0x6d, 0xc4, 0x15, 0xf9, 0x31,
	0x58, 0x2b, 0xec, 0xac, 0xd9, 0xdd, 0x14, 0xca, 0x3f, 0xcd, 0xbf, 0x80, 0xb2, 0xb6, 0x49, 0x55,
	0x52, 0x38, 0xf5, 0x12, 0xed, 0x64, 0x67, 0xe6, 0xf7, 0x7d, 0x9f, 0x17, 0xee, 0x35, 0x4a, 0x1a,
	0x39, 0xd7, 0xb4, 0x2e, 0xec, 0x0f, 0xb3, 0x35, 0x86, 0xa5, 0x64, 0xb5, 0xc8, 0x95, 0x64, 0x5a,
	0x9d, 0x33, 0x5d, 0xeb, 0xf8, 0x71, 0x29, 0x65, 0x59, 0xd1, 0xdc, 0xde, 0x67, 0x9b, 0x2f, 0x73,
	0x23, 0x6a, 0xd2, 0x26, 0xad, 0x9b, 0x76, 0x24, 0x09, 0xc0, 0xe7, 0xf4, 0x6d, 0x43, 0xda, 0x24,
	0xcf, 0xc1, 0x5f, 0xa6, 0xcd, 0xea, 0xa2, 0x21, 0x0c, 0xc1, 0xfd, 0x4a, 0x17, 0x91, 0x33, 0x75,
	0x66, 0x43, 0xbe, 0x3d, 0xe2, 0x5d, 0x18, 0x9e, 0xa7, 0xd5, 0x86, 0xa2, 0x83, 0xa9, 0x33, 0x0b,
	0x78, 0x5b, 0x24, 0x2f, 0xe1, 0xe8, 0xb5, 0xf8, 0xb9, 0x1d, 0xe1, 0xa4, 0x1b, 0xb9, 0xd6, 0x84,
	0xcf, 0xc0, 0xab, 0x84, 0x36, 0x91, 0x33, 0x75, 0x67, 0x93, 0xc5, 0x7d, 0x76, 0x55, 0x12, 0xeb,
	0x18, 0xdc, 0xb6, 0x25, 0x06, 0x26, 0x6f, 0x64, 0x41, 0x9d, 0x06, 0x3c, 0x86, 0x51, 0x2d, 0x33,
	0x51, 0x91, 0x65, 0x07, 0xbc, 0xab, 0xf0, 0x14, 0xfc, 0xac, 0x05, 0x59, 0x01, 0xb7, 0xf7, 0x2d,
	0xee, 0x95, 0xf4, 0x9d, 0x18, 0x81, 0x4f, 0x3f, 0x1a, 0xa1, 0x48, 0x47, 0xee, 0xd4, 0x99, 0xb9,
	0xbc, 0x2f, 0x93, 0x0c, 0x0e, 0x5b, 0x6a, 0x27, 0x3a, 0x02, 0x5f, 0x6f, 0xf2, 0x9c, 0xb4, 0xb6,
	0xdc, 0x31, 0xef, 0x4b, 0x7c, 0x01, 0x41, 0x37, 0xf4, 0xca, 0x58, 0xf4, 0x64, 0x11, 0xb3, 0x36,
	0x54, 0xd6, 0x87, 0xca, 0x56, 0x7d, 0xa8, 0x7c, 0xd7, 0x9c, 0x28, 0x38, 0xfa, 0x94, 0x56, 0xa2,
	0x48, 0xcd, 0xcd, 0xb8, 0x43, 0xf0, 0x72, 0x59, 0x90, 0xb5, 0x16, 0x70, 0x7b, 0x4e, 0x9e, 0x42,
	0xb8, 0x63, 0xfe, 0xcf, 0xdb, 0xc9, 0x12, 0xfc, 0x6e, 0x2b, 0x06, 0x30, 0xac, 0x64, 0x29, 0xd6,
	0xe1, 0x00, 0x0f, 0x61, 0xac, 0xa8, 0x14, 0xda, 0x90, 0x0a, 0x1d, 0xbc, 0x03, 0xb7, 0xde, 0x16,
	0xc2, 0x7c, 0xfe, 0x98, 0x6a, 0xfd, 0x5d, 0xaa, 0x22, 0x3c, 0xc0, 0x63, 0xc0, 0x15, 0xd5, 0x8d,
	0x22, 0x4d, 0x97, 0xfe, 0x77, 0x4f, 0x1e, 0x80, 0xb7, 0x94, 0x05, 0xe1, 0x18, 0xbc, 0x6d, 0xb8,
	0xe1, 0x00, 0x01, 0x46, 0x1f, 0xa4, 0x11, 0x39, 0x85, 0xce, 0xe2, 0x97, 0x03, 0xde, 0x19, 0xad,
	0x0b, 0x7c, 0xbf, 0xa3, 0xee, 0xb1, 0xd9, 0x45, 0x15, 0x3f, 0xb9, 0x3e, 0x81, 0xce, 0x58, 0x32,
	0xc0, 0x77, 0x2d, 0x09, 0x1f, 0xfe, 0xdd, 0x7c, 0xe9, 0x51, 0xc5, 0x8f, 0xae, 0xbb, 0xfe, 0xb3,
	0xe8, 0x0c, 0xc6, 0x7d, 0x6e, 0xb8, 0x87, 0x7c, 0xe5, 0x3b, 0xc6, 0xc9, 0xbf, 0x5a, 0xfa, 0xa5,
	0xd9, 0xc8, 0xbe, 0x8f, 0xd3, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x83, 0xed, 0xa5, 0x91, 0xad,
	0x03, 0x00, 0x00,
}
